function setPaperQuality()
set( gca                       , ...
    'FontName'   , 'Helvetica' , ...
    'FontSize'   , 16);
hTitle = get(gca, 'title');
hXLabel = get(gca, 'xlabel');
hYLabel = get(gca, 'ylabel');
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 20          );
set( hTitle                    , ...
    'FontSize'   , 24          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'on'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
end

