% datasets = {'50words','Adiac','ArrowHead','ARSim','Beef','BeetleFly',...
%     'BirdChicken','Car','CBF','Coffee','Computers','Chlorine',...
%     'CinECG','Cricket_X','Cricket_Y','Cricket_Z','DiatomSize',...
%     'DistalPhalanxOutlineAgeGroup','DistalPhalanxOutlineCorrect',...
%     'ECGFiveDays','Earthquakes','ElectricDevices','FaceAll','FaceFour',...
%     'FacesUCR','Fish','FordA','FordB','Gun_Point','HandOutlines', ...
%     'DistalPhalanxTW','Herring','LargeKitchenAppliances',...
%     'Haptics','InlineSkate','ItalyPower','Lighting2',...
%     'Lighting7','MALLAT','MedicalImages','MoteStrain','NonInv_ECG1',...
%     'MiddlePhalanxOutlineAgeGroup','MiddlePhalanxOutlineCorrect',...
%     'MiddlePhalanxTW','PhalangesOutlinesCorrect','Plane',...
%     'ProximalPhalanxOutlineAgeGroup','ProximalPhalanxOutlineCorrect',...
%     'ProximalPhalanxTW','RefrigerationDevices',...
%     'NonInv_ECG2','OliveOil','OSULeaf','SonyAIBO1','SonyAIBO2',...
%     'ScreenType','ShapeletSim','ShapesAll','SmallKitchenAppliances',...
%     'StarLight','SwedishLeaf','Symbols','Synthetic','Trace',...
%     'Two_Patterns','TwoLeadECG','uWGestureX','uWGestureY','uWGestureZ',...
%     'ToeSegmentation1','ToeSegmentation2','Wafer','WordsSynonyms','Yoga'};
datasets = {'ShapeletSim', 'ProximalPhalanxOutlineCorrect', ...
    'Plane', 'MiddlePhalanxTW', 'InlineSkate', 'Fish', 'FaceAll', ...
    'DistalPhalanxOutlineAgeGroup', 'CinECG', 'Car', ...
    'Two_Patterns', 'Trace', 'Synthetic', 'SwedishLeaf', ...
    'PhalangesOutlinesCorrect', 'OSULeaf','MiddlePhalanxOutlineCorrect',...
    'Haptics','Earthquakes','Cricket_Z','Cricket_Y','StarLight',...
    'SmallKitchenAppliances','ShapesAll','ScreenType', 'RefrigerationDevices',...
    'NonInv_ECG1', 'NonInv_ECG2', 'LargeKitchenAppliances', 'FordA', ...
    'FordB','ElectricDevices', 'ARSim'};
fullSH = fopen('hvMots.sh', 'w');
fprintf(fullSH, '#!/bin/sh\n');
for i = 1:length(datasets)
    fprintf(fullSH, 'bsub < ./hvMots_%s.sh\n', datasets{i});
    confID = fopen(['config' datasets{i}], 'w');
    fprintf(confID, 'Directory\tdatasets\n');
    fprintf(confID, datasets{i});
    fprintf(confID, '\tTRAIN\t');
    fprintf(confID, '%s/%s_TRAIN\t', datasets{i}, datasets{i});
    fprintf(confID, '%s/%s_TEST\n', datasets{i}, datasets{i});
    fprintf(confID, datasets{i});
    fprintf(confID, '\tTRAIN\t');
    fprintf(confID, '%s/%s_TRAIN\t', datasets{i}, datasets{i});
    fprintf(confID, '%s/%s_TEST\n', datasets{i}, datasets{i});
    fclose(confID);
    confID = fopen(['hvMots_' datasets{i} '.sh'], 'w');
    fprintf(confID, '#!/bin/sh\n');
    fprintf(confID, '#BSUB -J HV-loo-%s\n', datasets{i});
    fprintf(confID, '#BSUB -e HV-%s.err.txt\n', datasets{i});
    fprintf(confID, '#BSUB -o HV-%s.out.txt\n', datasets{i});
    fprintf(confID, '#BSUB -n 16\n');
    fprintf(confID, '#BSUB -R "span[ptile=32]"\n');
    fprintf(confID, '#BSUB -R "rusage[mem=8192]"\n');
    fprintf(confID, '#BSUB -M 8294304\n');
    fprintf(confID, 'cd ~/hvmots_loo && ./hvMots_red -config main.cfg -collection jobs/config%s', datasets{i});
    fclose(confID);
end