#!/bin/sh
bsub < ./hvMots_ShapeletSim.sh
bsub < ./hvMots_ProximalPhalanxOutlineCorrect.sh
bsub < ./hvMots_Plane.sh
bsub < ./hvMots_MiddlePhalanxTW.sh
bsub < ./hvMots_InlineSkate.sh
bsub < ./hvMots_Fish.sh
bsub < ./hvMots_FaceAll.sh
bsub < ./hvMots_DistalPhalanxOutlineAgeGroup.sh
bsub < ./hvMots_CinECG.sh
bsub < ./hvMots_Car.sh
bsub < ./hvMots_Two_Patterns.sh
bsub < ./hvMots_Trace.sh
bsub < ./hvMots_Synthetic.sh
bsub < ./hvMots_SwedishLeaf.sh
bsub < ./hvMots_PhalangesOutlinesCorrect.sh
bsub < ./hvMots_OSULeaf.sh
bsub < ./hvMots_MiddlePhalanxOutlineCorrect.sh
bsub < ./hvMots_Haptics.sh
bsub < ./hvMots_Earthquakes.sh
bsub < ./hvMots_Cricket_Z.sh
bsub < ./hvMots_Cricket_Y.sh
bsub < ./hvMots_StarLight.sh
bsub < ./hvMots_SmallKitchenAppliances.sh
bsub < ./hvMots_ShapesAll.sh
bsub < ./hvMots_ScreenType.sh
bsub < ./hvMots_RefrigerationDevices.sh
bsub < ./hvMots_NonInv_ECG1.sh
bsub < ./hvMots_NonInv_ECG2.sh
bsub < ./hvMots_LargeKitchenAppliances.sh
bsub < ./hvMots_FordA.sh
bsub < ./hvMots_FordB.sh
bsub < ./hvMots_ElectricDevices.sh
bsub < ./hvMots_ARSim.sh
